# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
