# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openicon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
